CREATE TABLE IF NOT EXISTS attendee(
    id TEXT NOT NULL PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES events(id) ONDELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ONDELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
),