CREATE TABLE IF NOT EXISTS events(
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    creator_id TEXT NOT NULL REFERENCES users(id) ONDELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);