basePath: /api/v1
definitions:
  routes.EventRequest:
    properties:
      name:
        example: Hackathon
        minLength: 2
        type: string
    required:
    - name
    type: object
  routes.EventResponse:
    properties:
      created_at:
        example: "2026-01-06T15:00:00Z"
        type: string
      creator_id:
        example: usr_12345
        type: string
      id:
        example: evt_12345
        type: string
      name:
        example: Hackathon
        type: string
    type: object
  utils.ErrorResponseSchema:
    properties:
      error:
        example: Invalid request
        type: string
      success:
        example: false
        type: boolean
    type: object
  utils.SuccessResponseSchema:
    properties:
      data: {}
      message:
        example: User created
        type: string
      success:
        example: true
        type: boolean
    type: object
host: localhost:5000
info:
  contact: {}
  description: This is an api server for making events and attending events.
  title: Go Gin Doc
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user using username and password
      parameters:
      - description: Login payload
        in: body
        name: body
        required: true
        schema:
          properties:
            password:
              type: string
            username:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/utils.SuccessResponseSchema'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
      summary: Login user
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user account using name, username, and password
      parameters:
      - description: Register payload
        in: body
        name: body
        required: true
        schema:
          properties:
            name:
              type: string
            password:
              type: string
            username:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            $ref: '#/definitions/utils.SuccessResponseSchema'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
      summary: Register a new user
      tags:
      - Auth
  /events:
    get:
      description: Retrieve all events from the system
      produces:
      - application/json
      responses:
        "200":
          description: No events yet
          schema:
            $ref: '#/definitions/utils.SuccessResponseSchema'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
      security:
      - BearerAuth: []
      summary: Get all events
      tags:
      - Event
    post:
      consumes:
      - application/json
      description: Create a new event in the system
      parameters:
      - description: Event payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/routes.EventRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Event created successfully
          schema:
            $ref: '#/definitions/utils.SuccessResponseSchema'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "401":
          description: Unauthorized user
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "409":
          description: Event already exists
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
      security:
      - BearerAuth: []
      summary: Create a new event
      tags:
      - Event
  /events/{id}:
    delete:
      description: Delete an existing event by its ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Event deleted successfully
          schema:
            $ref: '#/definitions/utils.SuccessResponseSchema'
        "400":
          description: Invalid event ID
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "500":
          description: Failed to delete event
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
      security:
      - BearerAuth: []
      summary: Delete an event
      tags:
      - Event
    get:
      description: Retrieve details of a specific event by its ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Event details retrieved successfully
          schema:
            $ref: '#/definitions/routes.EventResponse'
        "400":
          description: Invalid event ID
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "404":
          description: No event found
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
      security:
      - BearerAuth: []
      summary: Get a single event
      tags:
      - Event
    put:
      consumes:
      - application/json
      description: Update the name of an existing event by its ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      - description: Update payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/routes.EventRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Event updated successfully
          schema:
            $ref: '#/definitions/routes.EventResponse'
        "400":
          description: Invalid event ID or request body
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "404":
          description: Event not found
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponseSchema'
      security:
      - BearerAuth: []
      summary: Update an event
      tags:
      - Event
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
